INSERT INTO instituicao (nome) values ("Ifac - Instituto Federal do Acre");
INSERT INTO instituicao (nome) values ("Ufac - Universidade Federal do Acre");
INSERT INTO instituicao (nome) values ("Uninorte - União Educacional do Norte");
INSERT INTO instituicao (nome) values ("Iesacre - Instituição de Ensino Superior do Acre");
INSERT INTO instituicao (nome) values ("Fadisi - Faculdade Diocesana São José");
INSERT INTO instituicao (nome) values ("Faao - Faculdade da Amazônia Ocidental");
INSERT INTO instituicao (nome) values ("Fameta - Faculdade Meta");
INSERT INTO instituicao (nome) values ("Uneal - Universidade Estadual de Alagoas");
INSERT INTO instituicao (nome) values ("Uncisal - Universidade Estadual de Ciências da Saúde de Alagoas");
INSERT INTO instituicao (nome) values ("Ifal - Instituto Federal de Alagoas");
INSERT INTO instituicao (nome) values ("Ufal - Universidade Federal de Alagoas");
INSERT INTO instituicao (nome) values ("CESMAC - Centro de Estudos Superiores de Maceió");
INSERT INTO instituicao (nome) values ("FAA & IESA - Associação de Ensino Superior de Alagoas");
INSERT INTO instituicao (nome) values ("FACIMA - Faculdade da Cidade de Maceió");
INSERT INTO instituicao (nome) values ("FAP - Faculdade Pitágoras");
INSERT INTO instituicao (nome) values ("FITS - Faculdade Integrada Tiradentes");
INSERT INTO instituicao (nome) values ("Ueap - Universidade Estadual do Amapá");
INSERT INTO instituicao (nome) values ("Ifap - Instituto Federal do Amapá");
INSERT INTO instituicao (nome) values ("Unifap - Universidade Federal do Amapá");
INSERT INTO instituicao (nome) values ("CEAP - Centro de Ensino Superior do Amapá");
INSERT INTO instituicao (nome) values ("FABRAN - Faculdade Brasil Norte");
INSERT INTO instituicao (nome) values ("FAMA - Faculdade do Amapá");
INSERT INTO instituicao (nome) values ("FESAM - Faculdade de Ensino Superior da Amazônia");
INSERT INTO instituicao (nome) values ("IESAP - Instituto de Ensino Superior do Amapá");
INSERT INTO instituicao (nome) values ("IMMES - Instituto Macapaense do Melhor Ensino Superior");
INSERT INTO instituicao (nome) values ("META - Faculdade Meta");
INSERT INTO instituicao (nome) values ("SEAMA - Faculdade SEAMA");
INSERT INTO instituicao (nome) values ("Uea - Universidade do Estado do Amazonas");
INSERT INTO instituicao (nome) values ("Ifam - Instituto Federal do Amazonas");
INSERT INTO instituicao (nome) values ("Ufam - Universidade Federal do Amazonas");
INSERT INTO instituicao (nome) values ("ULBRA - Universidade Luterana do Brasil");
INSERT INTO instituicao (nome) values ("FSDB - Faculdade Salesiana Dom Bosco");
INSERT INTO instituicao (nome) values ("Ciesa - Centro Universitário de Ensino Superior do Amazonas");
INSERT INTO instituicao (nome) values ("UNINILTONLINS - Centro Universitário Nilton Lins");
INSERT INTO instituicao (nome) values ("Cesf - Instituto de Ensino Superior Fucapi");
INSERT INTO instituicao (nome) values ("FT - Faculdade Táhirih");
INSERT INTO instituicao (nome) values ("Fametro - Faculdade Metropolitana de Manaus");
INSERT INTO instituicao (nome) values ("FMF - Faculdade Martha Falcão");
INSERT INTO instituicao (nome) values ("Fal - Faculdade Literatus");
INSERT INTO instituicao (nome) values ("Unisalle - Faculdade La Salle");
INSERT INTO instituicao (nome) values ("Iaes - Faculdade do Amazonas");
INSERT INTO instituicao (nome) values ("FOM - Faculdade de Odontologia de Manaus");
INSERT INTO instituicao (nome) values ("FBNCTSB - Faculdade Boas Novas de Ciências Teológicas, Sociais e Biotecnológicas");
INSERT INTO instituicao (nome) values ("Esbam - Escola Superior Batista do Amazonas");
INSERT INTO instituicao (nome) values ("Uninorte - Centro Universitário do Norte");
INSERT INTO instituicao (nome) values ("Unip - Universidade Paulista");
INSERT INTO instituicao (nome) values ("UECE - Universidade Estadual do Ceará");
INSERT INTO instituicao (nome) values ("URCA - Universidade Regional do Cariri");
INSERT INTO instituicao (nome) values ("UVA - Universidade Estadual Vale do Acaraú");
INSERT INTO instituicao (nome) values ("IFCE - Instituto Federal do Ceará");
INSERT INTO instituicao (nome) values ("UFC - Universidade Federal do Ceará");
INSERT INTO instituicao (nome) values ("UNILAB - Universidade Federal de Integração Luso-Afro-Brasileira");
INSERT INTO instituicao (nome) values ("UFCA - Universidade Federal do Cariri");
INSERT INTO instituicao (nome) values ("CENTEC - Falcudade de Tecnologia CENTEC (Na prática, é como se fosse estadual)");
INSERT INTO instituicao (nome) values ("FAMETRO - Faculdade Metropolitana de Fortaleza");
INSERT INTO instituicao (nome) values ("FCC - Faculdade Católica do Ceará");
INSERT INTO instituicao (nome) values ("FCF - Faculdade Católica de Fortaleza");
INSERT INTO instituicao (nome) values ("FCRS - Faculdade Católica Rainha do Sertão");
INSERT INTO instituicao (nome) values ("INTA - Instituto Superior de Teologia Aplicada");
INSERT INTO instituicao (nome) values ("IESF - Instituto de Ensino Superior de Fortaleza");
INSERT INTO instituicao (nome) values ("UNIFOR - Universidade de Fortaleza");
INSERT INTO instituicao (nome) values ("FAECE - Faculdade de Ensino e Cultura do Ceará");
INSERT INTO instituicao (nome) values ("FAFOR - Faculdade de Fortaleza");
INSERT INTO instituicao (nome) values ("FATENE - Faculdade Terra Nordeste");
INSERT INTO instituicao (nome) values ("FANOR - Faculdades Nordeste");
INSERT INTO instituicao (nome) values ("FATE - Faculdade Ateneu");
INSERT INTO instituicao (nome) values ("UNICHRISTUS - Centro Universitário Christus");
INSERT INTO instituicao (nome) values ("FAC - Faculdades Cearenses");
INSERT INTO instituicao (nome) values ("FACE - Faculdade Evolutivo");
INSERT INTO instituicao (nome) values ("FALS - Faculdade de Ciências Aplicadas Doutor Leão Sampaio");
INSERT INTO instituicao (nome) values ("FAP - Faculdade Paraíso do Ceará");
INSERT INTO instituicao (nome) values ("FA7 - Faculdade 7 de Setembro");
INSERT INTO instituicao (nome) values ("FFB - Faculdade Farias Brito");
INSERT INTO instituicao (nome) values ("ESTÁCIO FIC - Faculdade Integrada do Ceará");
INSERT INTO instituicao (nome) values ("FJN - Faculdade de Juazeiro do Norte");
INSERT INTO instituicao (nome) values ("FLF - Faculdade Luciano Feijão");
INSERT INTO instituicao (nome) values ("FMJ - Faculdade de Medicina de Juazeiro do Norte");
INSERT INTO instituicao (nome) values ("FTA - Faculdade de Tecnologia Apoena");
INSERT INTO instituicao (nome) values ("FVJ - Faculdade Vale do Jaguaribe");
INSERT INTO instituicao (nome) values ("FGF - Faculdade Integrada da Grande Fortaleza");
INSERT INTO instituicao (nome) values ("FAS - Faculdade Ari de Sá");
INSERT INTO instituicao (nome) values ("UPA - Universidade Patativa do Assaré");
INSERT INTO instituicao (nome) values ("ESCS - Escola Superior de Ciências da Saúde");
INSERT INTO instituicao (nome) values ("IFB - Instituto Federal de Brasília");
INSERT INTO instituicao (nome) values ("UnB - Universidade de Brasília");
INSERT INTO instituicao (nome) values ("UCB - Universidade Católica de Brasília");
INSERT INTO instituicao (nome) values ("UPIS - União Pioneira de Integração Social");
INSERT INTO instituicao (nome) values ("CEUB - Centro Universitário de Brasília");
INSERT INTO instituicao (nome) values ("FATE - Faculdade Ateneu");
INSERT INTO instituicao (nome) values ("FACIPLAC - Faculdade de Ciência e Tecnologia do Planalto Central");
INSERT INTO instituicao (nome) values ("FACITEC - Faculdade de Ciências Sociais e Tecnológicas");
INSERT INTO instituicao (nome) values ("FACICESP - FACULDADES INTEGRADAS ICESP - UNICESP - Brasília");
INSERT INTO instituicao (nome) values ("FASEP - Faculdade Serrana");
INSERT INTO instituicao (nome) values ("FTB - Faculdades Integradas da Terra de Brasília");
INSERT INTO instituicao (nome) values ("IESB - Instituto de Educação Superior de Brasília");
INSERT INTO instituicao (nome) values ("SENAC - Faculdade Senac - Distrito Federal");
INSERT INTO instituicao (nome) values ("UDF - Centro Universitário do Distrito Federal");
INSERT INTO instituicao (nome) values ("UNIEURO - Centro Universitário Euroamericano");
INSERT INTO instituicao (nome) values ("UNIDESC - Centro Universitário de Desenvolvimento do Centro Oeste");
INSERT INTO instituicao (nome) values ("UNIP - Universidade Paulista");
INSERT INTO instituicao (nome) values ("UNIPLAN - Centro Universitário Planalto do Distrito Federal");
INSERT INTO instituicao (nome) values ("UNISEB - Centro Universitário Estácio UniSEB - Brasília");
INSERT INTO instituicao (nome) values ("UNOPAR - Universidade Norte do Paraná");
INSERT INTO instituicao (nome) values ("FACELI - Faculdade de Ensino Superior de Linhares");
INSERT INTO instituicao (nome) values ("FAMES - Faculdade De Musica do Espírito Santo Mauricio de Oliveira");
INSERT INTO instituicao (nome) values ("IFES - Instituto Federal do Espírito Santo");
INSERT INTO instituicao (nome) values ("UFES - Universidade Federal do Espírito Santo");
INSERT INTO instituicao (nome) values ("EMESCAM - Escola Superior de Ciências da Santa Casa de Misericórdia de Vitória");
INSERT INTO instituicao (nome) values ("FAPECS - Instituto de Pesquisa em Ciências da Saude");
INSERT INTO instituicao (nome) values ("UVV - Universidade Vila Velha");
INSERT INTO instituicao (nome) values ("UNESC - Centro Universitário do Espírito Santo");
INSERT INTO instituicao (nome) values ("FAESA - Faculdades Integradas Espírito-Santenses");
INSERT INTO instituicao (nome) values ("UCL - Faculdade do Centro Leste");
INSERT INTO instituicao (nome) values ("Favi/FACES - Faculdade do Espírito Santo");
INSERT INTO instituicao (nome) values ("ESFA - Escola Superior São Francisco de Assis");
INSERT INTO instituicao (nome) values ("CUSC - Centro Universitário São Camilo");
INSERT INTO instituicao (nome) values ("FAFIA - Faculdade de Filosofia Ciências e Letras de Alegre");
INSERT INTO instituicao (nome) values ("FCB - Faculdade Castelo Branco");
INSERT INTO instituicao (nome) values ("CESAT - Escola de Ensino Superior Anísio Teixeira");
INSERT INTO instituicao (nome) values ("CESV - Centro de Ensino Superior de Vitória");
INSERT INTO instituicao (nome) values ("DOCTUM - Rede de Ensino Doctum");
INSERT INTO instituicao (nome) values ("FABAVI - Faculdade Batista de Vitoria");
INSERT INTO instituicao (nome) values ("FAACZ - Faculdade de Aracruz");
INSERT INTO instituicao (nome) values ("FACE - Faculdade Casa do Estudante");
INSERT INTO instituicao (nome) values ("FACES - Faculdade do Espírito Santo");
INSERT INTO instituicao (nome) values ("FASE - Faculdade da Serra");
INSERT INTO instituicao (nome) values ("FAVI - Associação Vitoriana de Ensino Superior");
INSERT INTO instituicao (nome) values ("FCMV - Faculdade Candido Mendes de Vitória");
INSERT INTO instituicao (nome) values ("FDV - Faculdades Integradas de Vitória");
INSERT INTO instituicao (nome) values ("FUCAPE - Fundação Instituto Capixaba de Pesquisas em Contabilidade, Economia e Finanças");
INSERT INTO instituicao (nome) values ("MULTIVIX - Faculdade Brasileira");
INSERT INTO instituicao (nome) values ("PIO XII - Faculdade de Estudos Sociais do Espírito Santo");
INSERT INTO instituicao (nome) values ("SABERES - Faculdade Saberes");
INSERT INTO instituicao (nome) values ("UNESA - Universidade Estácio de Sá");
INSERT INTO instituicao (nome) values ("UniRV (FESURV) - Universidade de Rio Verde");
INSERT INTO instituicao (nome) values ("UEG - Universidade Estadual de Goiás");
INSERT INTO instituicao (nome) values ("IFG - Instituto Federal de Goiás");
INSERT INTO instituicao (nome) values ("UFG - Universidade Federal de Goiás");
INSERT INTO instituicao (nome) values ("IF Goiano - Instituto Federal Goiano");
INSERT INTO instituicao (nome) values ("UFCat - Universidade Federal de Catalão");
INSERT INTO instituicao (nome) values ("UFJat - Universidade Federal de Jataí");
INSERT INTO instituicao (nome) values ("IPOG - Instituto de Pós-Graduação");
INSERT INTO instituicao (nome) values ("PUC - Pontifícia Universidade Católica de Goiás");
INSERT INTO instituicao (nome) values ("UNIVERSO - Universidade Salgado de Oliveira");
INSERT INTO instituicao (nome) values ("Fac - Faculdade Católica de Anápolis");
INSERT INTO instituicao (nome) values ("ULBRA - Universidade Luterana do Brasil");
INSERT INTO instituicao (nome) values ("Fasug - Faculdade do Sudeste Goiano");
INSERT INTO instituicao (nome) values ("ALFA - Faculdade Alves Faria");
INSERT INTO instituicao (nome) values ("CESUC - Centro de Ensino Superior de Catalão");
INSERT INTO instituicao (nome) values ("FACERES - Faculdade de Ceres");
INSERT INTO instituicao (nome) values ("FACER - Faculdade de Ciências de Rubiataba");
INSERT INTO instituicao (nome) values ("FACEG - Faculdade Evangelica de Goianesia");
INSERT INTO instituicao (nome) values ("FAA - Faculdade Anhanguera de Anápolis");
INSERT INTO instituicao (nome) values ("FASAM - Faculdade Sul-Americana");
INSERT INTO instituicao (nome) values ("IESRIVER - Instituto de Ensino Superior de Rio Verde");
INSERT INTO instituicao (nome) values ("INSJAR - Instituto Jordão de Arruda");
INSERT INTO instituicao (nome) values ("UNESA - Universidade Estácio de Sá");
INSERT INTO instituicao (nome) values ("UNIP - Universidade Paulista");
INSERT INTO instituicao (nome) values ("UNIFASC - Faculdade Santa Rita de Cássia");
INSERT INTO instituicao (nome) values ("UniEvangelica - Universidade Evangélica");
INSERT INTO instituicao (nome) values ("Unianhanguera - Universidade Anhanguera");
INSERT INTO instituicao (nome) values ("IAESUP - Faculdades e Colégio Aphonsiano");
INSERT INTO instituicao (nome) values ("IUESO - Instituto Unificado de Ensino Superior Objetivo");
INSERT INTO instituicao (nome) values ("FMB - Faculdade Montes Belos");
INSERT INTO instituicao (nome) values ("UEMA - Universidade Estadual do Maranhão");
INSERT INTO instituicao (nome) values ("UEMASUL - Universidade Estadual da Região Tocantina do Maranhão");
INSERT INTO instituicao (nome) values ("IEMA - Instituto Estadual do Maranhão");
INSERT INTO instituicao (nome) values ("IFMA - Instituto Federal do Maranhão");
INSERT INTO instituicao (nome) values ("UFMA - Universidade Federal do Maranhão");
INSERT INTO instituicao (nome) values ("CEST - Faculdade Santa Terezinha (São Luís)");
INSERT INTO instituicao (nome) values ("FACEM - Faculdade do Estado do Maranhão (São Luís)");
INSERT INTO instituicao (nome) values ("FACEMA - Faculdade de Ciências e Tecnologia do Maranhão (Caxias)");
INSERT INTO instituicao (nome) values ("FACIMP - Faculdade de Imperatriz");
INSERT INTO instituicao (nome) values ("FAMA - Faculdade Atenas Maranhense");
INSERT INTO instituicao (nome) values ("FAP - Faculdade do Baixo Paranaíba (Chapadinha)");
INSERT INTO instituicao (nome) values ("FEST - Faculdade de Educação Santa Terezinha (Imperatriz)");
INSERT INTO instituicao (nome) values ("FSL - Faculdade São Luís");
INSERT INTO instituicao (nome) values ("IESF - Instituto de Ensino Superior Franciscano (Paço do Lumiar)");
INSERT INTO instituicao (nome) values ("IMEC - Instituto Maranhense de Ensino e Cultura (São Luís)");
INSERT INTO instituicao (nome) values ("UNDB - Unidade de Ensino Superior Dom Bosco (São Luís)");
INSERT INTO instituicao (nome) values ("UNICEUMA - Centro Universitário do Maranhão (São Luís)");
INSERT INTO instituicao (nome) values ("UNEMAT - Universidade do Estado de Mato Grosso");
INSERT INTO instituicao (nome) values ("IFMT - Instituto Federal do Mato Grosso");
INSERT INTO instituicao (nome) values ("UFMT - Universidade Federal de Mato Grosso");
INSERT INTO instituicao (nome) values ("CATHEDRAL - Faculdades Cathedral-Barra do Garças");
INSERT INTO instituicao (nome) values ("EDUVALE - Faculdade de Ciências Sociais Aplicadas do Vale do São Lourenço");
INSERT INTO instituicao (nome) values ("FADAF - Faculdade de Direito de Alta Floresta");
INSERT INTO instituicao (nome) values ("FAPAN - Faculdade do Pantanal");
INSERT INTO instituicao (nome) values ("FASIPE - Faculdade FASIPE");
INSERT INTO instituicao (nome) values ("ICEC - Instituto Cuiabá de Ensino e Cultura");
INSERT INTO instituicao (nome) values ("IESMT - Instituto de Ensino Superior de Mato Grosso");
INSERT INTO instituicao (nome) values ("LA SALLE - Faculdade La Salle");
INSERT INTO instituicao (nome) values ("ULBRA - Universidade Luterana do Brasil - EAD");
INSERT INTO instituicao (nome) values ("UNIC - Universidade de Cuiabá");
INSERT INTO instituicao (nome) values ("UNIP - Universidade Paulista");
INSERT INTO instituicao (nome) values ("UNIRONDON - Centro Universitário Cândido Rondon");
INSERT INTO instituicao (nome) values ("UNIVAG - Centro Universitário de Várzea Grande");
INSERT INTO instituicao (nome) values ("UNIVAR - Universidades Unidas do Vale do Araguaia-Barra do Garças");
INSERT INTO instituicao (nome) values ("UEMS - Universidade Estadual do Mato Grosso do Sul");
INSERT INTO instituicao (nome) values ("UFGD - Universidade Federal da Grande Dourados");
INSERT INTO instituicao (nome) values ("IFMS - Instituto Federal de Mato Grosso do Sul");
INSERT INTO instituicao (nome) values ("UFMS - Universidade Federal do Mato Grosso do Sul");
INSERT INTO instituicao (nome) values ("UFPAN - Universidade Federal do Pantanal");
INSERT INTO instituicao (nome) values ("UCDB - Universidade Católica Dom Bosco");
INSERT INTO instituicao (nome) values ("AEMS - Faculdades Integradas de Três Lagoas");
INSERT INTO instituicao (nome) values ("FCG - Faculdade Campo Grande");
INSERT INTO instituicao (nome) values ("FACSUL - Faculdade Mato Grosso do Sul");
INSERT INTO instituicao (nome) values ("UNAES - Centro Universitário de Campo Grande");
INSERT INTO instituicao (nome) values ("UNIDERP - Universidade para o Desenvolvimento do Estado e Região do Pantanal");
INSERT INTO instituicao (nome) values ("UNIGRAN - Centro Universitário da Grande Dourados");
INSERT INTO instituicao (nome) values ("FJP - Fundação João Pinheiro");
INSERT INTO instituicao (nome) values ("UEMG - Universidade do Estado de Minas Gerais");
INSERT INTO instituicao (nome) values ("UNIMONTES - Universidade Estadual de Montes Claros");
INSERT INTO instituicao (nome) values ("CEFET-MG - Centro Federal de Educação Tecnológica de Minas Gerais");
INSERT INTO instituicao (nome) values ("IFMG - Instituto Federal de Minas Gerais");
INSERT INTO instituicao (nome) values ("IFNMG - Instituto Federal do Norte de Minas Gerais");
INSERT INTO instituicao (nome) values ("IFSM - Instituto Federal do Sudeste de Minas");
INSERT INTO instituicao (nome) values ("IFSULDEMINAS - Instituto Federal do Sul de Minas");
INSERT INTO instituicao (nome) values ("IFTM - Instituto Federal do Triângulo Mineiro");
INSERT INTO instituicao (nome) values ("UFJF - Universidade Federal de Juiz de Fora");
INSERT INTO instituicao (nome) values ("UFLA - Universidade Federal de Lavras");
INSERT INTO instituicao (nome) values ("UFMG - Universidade Federal de Minas Gerais");
INSERT INTO instituicao (nome) values ("UFOP - Universidade Federal de Ouro Preto");
INSERT INTO instituicao (nome) values ("UFSJ - Universidade Federal de São João Del Rei");
INSERT INTO instituicao (nome) values ("UFTM - Universidade Federal do Triângulo Mineiro");
INSERT INTO instituicao (nome) values ("UFU - Universidade Federal de Uberlândia");
INSERT INTO instituicao (nome) values ("UFV - Universidade Federal de Viçosa");
INSERT INTO instituicao (nome) values ("UFVJM - Universidade Federal dos Vales do Jequitinhonha e Mucuri");
INSERT INTO instituicao (nome) values ("UNIFAL - Universidade Federal de Alfenas");
INSERT INTO instituicao (nome) values ("UNIFEI - Universidade Federal de Itajubá");
INSERT INTO instituicao (nome) values ("APM-MG - Academia de Polícia Militar de Minas Gerais");
INSERT INTO instituicao (nome) values ("EEK - Escola de Engenharia Kennedy");
INSERT INTO instituicao (nome) values ("EEWB - Escola de Enfermagem Wenceslau Braz");
INSERT INTO instituicao (nome) values ("ESDHC - Escola Superior Dom Helder Câmara");
INSERT INTO instituicao (nome) values ("FACAPA - Faculdade Católica de Pouso Alegre");
INSERT INTO instituicao (nome) values ("FADMINAS - Faculdades Integradas Adventistas de Minas Gerais");
INSERT INTO instituicao (nome) values ("FAGAMMON - Faculdade Presbiteriana Gammon");
INSERT INTO instituicao (nome) values ("FDSM - Faculdade de Direito do Sul de Minas");
INSERT INTO instituicao (nome) values ("FACECA - Faculdade Cenecista de Varginha");
INSERT INTO instituicao (nome) values ("FASF/Unisa - Faculdade de Filosofia, Ciências e Letras do Alto São Francisco");
INSERT INTO instituicao (nome) values ("FAZU - Faculdades Associadas de Uberaba");
INSERT INTO instituicao (nome) values ("FCMMG - Faculdade de Ciências Médicas de Minas Gerais");
INSERT INTO instituicao (nome) values ("FCMS/JF - Faculdade de Ciências Médicas e da Saúde de Juiz de Fora");
INSERT INTO instituicao (nome) values ("FMG - Faculdade Metodista Granbery");
INSERT INTO instituicao (nome) values ("FMIT - Faculdade de Medicina de Itajubá");
INSERT INTO instituicao (nome) values ("FUNJOB - Faculdade de Medicina de Barbacena");
INSERT INTO instituicao (nome) values ("FUMEC - Fundação Mineira de Educação e Cultura");
INSERT INTO instituicao (nome) values ("FUNCESI - Fundação Comunitária de Ensino Superior de Itabira");
INSERT INTO instituicao (nome) values ("INATEL - Instituto Nacional de Telecomunicações");
INSERT INTO instituicao (nome) values ("IESP - Instituto de Educação Superior de Patrocínio");
INSERT INTO instituicao (nome) values ("PUCMG - Pontifícia Universidade Católica de Minas Gerais");
INSERT INTO instituicao (nome) values ("UIT - Universidade de Itaúna");
INSERT INTO instituicao (nome) values ("UNIARAXÁ - Centro Universitário do Planalto de Araxá");
INSERT INTO instituicao (nome) values ("UNIBH - Centro Universitário de Belo Horizonte");
INSERT INTO instituicao (nome) values ("UNICERP - Centro Universitário do Cerrado - Patrocínio");
INSERT INTO instituicao (nome) values ("UNIFORMG - Centro Universitário de Formiga");
INSERT INTO instituicao (nome) values ("UNILESTE - Centro Universitário do Leste de Minas Gerais");
INSERT INTO instituicao (nome) values ("UNIPAC - Universidade Presidente Antônio Carlos");
INSERT INTO instituicao (nome) values ("UNIPAM - Centro Universitário de Patos de Minas");
INSERT INTO instituicao (nome) values ("UNITRI - Centro Universitário do Triângulo");
INSERT INTO instituicao (nome) values ("UNIUBE - Universidade de Uberaba");
INSERT INTO instituicao (nome) values ("UNIVAS - Universidade do Vale do Sapucaí");
INSERT INTO instituicao (nome) values ("UNIVALE - Universidade Vale do Rio Doce");
INSERT INTO instituicao (nome) values ("UNIVERSO - Universidade Salgado de Oliveira");
INSERT INTO instituicao (nome) values ("CUEA - Centro Universitário Eaprenda Elearning");
INSERT INTO instituicao (nome) values ("ASMEC - Associação Sul Mineira de Educação e Cultura");
INSERT INTO instituicao (nome) values ("CECON - Centro Educacional Conceição Nunes");
INSERT INTO instituicao (nome) values ("CENSI - Centro de Ensino Superior de Itabira");
INSERT INTO instituicao (nome) values ("DOCTUM - Rede de Ensino Doctum");
INSERT INTO instituicao (nome) values ("FAC - Faculdade Arquidiocesana de Curvelo");
INSERT INTO instituicao (nome) values ("FACEMG - Faculdade de Ensino de Minas Gerais");
INSERT INTO instituicao (nome) values ("FACESM - Faculdade de Ciências Sociais Aplicadas do Sul de Minas");
INSERT INTO instituicao (nome) values ("FACICA - Faculdade de Ciências da Saúde de Campos Gerais");
INSERT INTO instituicao (nome) values ("FACED - Faculdade de Ciências Contabeis de Divinópolis");
INSERT INTO instituicao (nome) values ("FACSUM - Faculdade do Sudeste Mineiro");
INSERT INTO instituicao (nome) values ("FACTU - Faculdade de Ciências e Tecnologia de Unaí");
INSERT INTO instituicao (nome) values ("FEAD - Faculdade de Estudos Administrativos de Minas Gerais");
INSERT INTO instituicao (nome) values ("FAVENORTE - Instituto Superior de Educação Verde Norte");
INSERT INTO instituicao (nome) values ("FEMG - Faculdade de Engenharia de Minas Gerais");
INSERT INTO instituicao (nome) values ("FJF - Faculdade Juiz de Fora");
INSERT INTO instituicao (nome) values ("FMC - Faculdades Milton Campos");
INSERT INTO instituicao (nome) values ("FPAS - Faculdade Pitágoras de Administração Superior");
INSERT INTO instituicao (nome) values ("FPMG - Faculdade Promove de Minas Gerais");
INSERT INTO instituicao (nome) values ("FPU - Faculdade Politécnica de Uberlândia");
INSERT INTO instituicao (nome) values ("FSA - Faculdades Santo Agostinho");
INSERT INTO instituicao (nome) values ("FUNEDI - Fundação Educacional de Divinópolis");
INSERT INTO instituicao (nome) values ("IBHES - Instituto Belo Horizonte de Ensino Superior");
INSERT INTO instituicao (nome) values ("INESC - Instituto de Ensino Superior Cenecista");
INSERT INTO instituicao (nome) values ("IPTAN - Instituto de Ensino Superior Presidente Tancredo Neves");
INSERT INTO instituicao (nome) values ("ISEC - Instituto Superior de Educação de Campos Gerais");
INSERT INTO instituicao (nome) values ("SECAL - Faculdade Santa Amélia");
INSERT INTO instituicao (nome) values ("UNA - Centro Universitário UNA");
INSERT INTO instituicao (nome) values ("UNIFENAS - Universidade de Alfenas José do Rosário Vellano");
INSERT INTO instituicao (nome) values ("UNILAVRAS - Centro Universitário de Lavras");
INSERT INTO instituicao (nome) values ("UNIVERSITAS - Centro Universitário de Itajubá");
INSERT INTO instituicao (nome) values ("UNIVIÇOSA - União de Ensino Superior de Viçosa");
INSERT INTO instituicao (nome) values ("UFRA - Universidade Federal Rural da Amazônia");
INSERT INTO instituicao (nome) values ("UFPA - Universidade Federal do Pará");
INSERT INTO instituicao (nome) values ("IFPA - Instituto Federal do Pará");
INSERT INTO instituicao (nome) values ("UFOPA - Universidade Federal do Oeste do Pará");
INSERT INTO instituicao (nome) values ("UNIFESSPA - Universidade Federal do Sul e Sudeste do Pará");
INSERT INTO instituicao (nome) values ("UEPA - Universidade do Estado do Pará");
INSERT INTO instituicao (nome) values ("CIABA - Centro de Instrução Almirante Braz de Aguiar");
INSERT INTO instituicao (nome) values ("CEAMA - Centro de Educação da Amazônia");
INSERT INTO instituicao (nome) values ("CESUPA - Centro Universitário do Pará");
INSERT INTO instituicao (nome) values ("ESMAC - Escola Superior Madre Celeste");
INSERT INTO instituicao (nome) values ("ESAMAZ - Escola Superior da Amazônia");
INSERT INTO instituicao (nome) values ("ESTÁCIO FAP - Estácio de Sá Faculdade do Pará");
INSERT INTO instituicao (nome) values ("FAAMA - Faculdade Adventista da Amazônia");
INSERT INTO instituicao (nome) values ("FAAM - Faculdade da Amazônia");
INSERT INTO instituicao (nome) values ("FAMAZ - Faculdade Metropolitana da Amazônia");
INSERT INTO instituicao (nome) values ("FABEL - Faculdade de Belém");
INSERT INTO instituicao (nome) values ("FACETE - Faculdade de Ensino Tecnológico do Estado do Pará");
INSERT INTO instituicao (nome) values ("FACI - Faculdade Ideal");
INSERT INTO instituicao (nome) values ("FACIP - Faculdade Ipiranga");
INSERT INTO instituicao (nome) values ("FAPAN - Faculdade Pan Amazônica");
INSERT INTO instituicao (nome) values ("FAPEN - Faculdade Paraense de Ensino");
INSERT INTO instituicao (nome) values ("FCAT - Faculdade de Castanhal");
INSERT INTO instituicao (nome) values ("FEAPA - Faculdade de Estudos Avançados do Pará");
INSERT INTO instituicao (nome) values ("FIT - Faculdades Integradas do Tapajós (Santarém)");
INSERT INTO instituicao (nome) values ("FIBRA - Faculdade Integrada Brasil Amazônia");
INSERT INTO instituicao (nome) values ("FMM - Faculdade Metropolitana de Marabá");
INSERT INTO instituicao (nome) values ("FPA - Faculdade Pan Americana");
INSERT INTO instituicao (nome) values ("IESAM - Instituto de Ensinos Superiores da Amazônia");
INSERT INTO instituicao (nome) values ("UNAMA - Universidade da Amazônia");
INSERT INTO instituicao (nome) values ("UNIP - Universidade Paulista");
INSERT INTO instituicao (nome) values ("UEPB - Universidade Estadual da Paraíba");
INSERT INTO instituicao (nome) values ("IFPB - Instituto Federal da Paraíba");
INSERT INTO instituicao (nome) values ("UFPB - Universidade Federal da Paraíba");
INSERT INTO instituicao (nome) values ("UFCG - Universidade Federal de Campina Grande");
INSERT INTO instituicao (nome) values ("UNIPÊ - Centro Universitário de João Pessoa");
INSERT INTO instituicao (nome) values ("ASPER - Associação Paraibana de Ensino Renovado");
INSERT INTO instituicao (nome) values ("DEVRY - DeVry João Pessoa");
INSERT INTO instituicao (nome) values ("ESAC - Escola Superior de Aviação Civil");
INSERT INTO instituicao (nome) values ("ESBJ - Faculdade Maurício de Nassau");
INSERT INTO instituicao (nome) values ("FAC - Faculdade de Campina Grande");
INSERT INTO instituicao (nome) values ("FACENE - Faculdade de Enfermagem Nova Esperança");
INSERT INTO instituicao (nome) values ("FAESNE - Faculdade de Ensino Superior do Nordeste");
INSERT INTO instituicao (nome) values ("FAFIC - Faculdade de Filosofía, Ciências e Letras de Cajazeiras");
INSERT INTO instituicao (nome) values ("FAFIL - Faculdade de Filosofía Ciências e Letras");
INSERT INTO instituicao (nome) values ("FAP - Faculdade Paraibana");
INSERT INTO instituicao (nome) values ("FARR - Faculdade Reinaldo Ramos");
INSERT INTO instituicao (nome) values ("FASER - Faculdade Santa Emília de Rodat");
INSERT INTO instituicao (nome) values ("FASP - Faculdade São Francisco da Paraíba");
INSERT INTO instituicao (nome) values ("FATEC - Faculdade de Tecnologia de João Pessoa");
INSERT INTO instituicao (nome) values ("FATECPB - Faculdade de Tecnología da Paraíba");
INSERT INTO instituicao (nome) values ("FCM - Faculdade de Ciências Médicas de Campina Grande");
INSERT INTO instituicao (nome) values ("FCM-PB - Faculdade de Ciências Médicas da Paraíba");
INSERT INTO instituicao (nome) values ("FEF - Faculdade Evilásio Formiga");
INSERT INTO instituicao (nome) values ("FESVIP - Faculdade de Enfermagem São Vicente de Paula");
INSERT INTO instituicao (nome) values ("FESP - Faculdade de Ensino Superior da Paraíba");
INSERT INTO instituicao (nome) values ("FIAA - Faculdades Integradas Anglo-Americano");
INSERT INTO instituicao (nome) values ("FIP - Faculdades Integradas de Patos");
INSERT INTO instituicao (nome) values ("FPB - Faculdade Potiguar da Paraíba");
INSERT INTO instituicao (nome) values ("FPB - Faculdade Internacional da Paraíba");
INSERT INTO instituicao (nome) values ("FPPD - Faculdade Paraibana de Processamento de Dados");
INSERT INTO instituicao (nome) values ("FSM - Faculdade Santa María");
INSERT INTO instituicao (nome) values ("IESP - Instituto de Educação Superior da Paraíba");
INSERT INTO instituicao (nome) values ("INPER - Insituto Paraibano de Ensino Renovado");
INSERT INTO instituicao (nome) values ("IPOG - Instituto de Pós-Graduação & Graduação");
INSERT INTO instituicao (nome) values ("ISEC - Instituto Superior de Educação de Cajazeiras");
INSERT INTO instituicao (nome) values ("LUMEN FAC - Faculdade de Ciências Contábeis Luiz Mendes");
INSERT INTO instituicao (nome) values ("UNIBRATEC - Faculdade de Tecnologia Ibratec");
INSERT INTO instituicao (nome) values ("UNIUOL - Faculdade de Tecnologia do Uniuol");
INSERT INTO instituicao (nome) values ("UNIPB - Faculdade Unida da Paraíba");
INSERT INTO instituicao (nome) values ("UNESPAR - Universidade Estadual do Paraná");
INSERT INTO instituicao (nome) values ("UEL - Universidade Estadual de Londrina");
INSERT INTO instituicao (nome) values ("UEM - Universidade Estadual de Maringá");
INSERT INTO instituicao (nome) values ("UENP - Universidade Estadual do Norte do Paraná");
INSERT INTO instituicao (nome) values ("UEPG - Universidade Estadual de Ponta Grossa");
INSERT INTO instituicao (nome) values ("UNICENTRO - Universidade Estadual do Centro Oeste");
INSERT INTO instituicao (nome) values ("UNIOESTE - Universidade Estadual do Oeste do Paraná");
INSERT INTO instituicao (nome) values ("IFPR - Instituto Federal do Paraná");
INSERT INTO instituicao (nome) values ("UTFPR - Universidade Tecnológica Federal do Paraná");
INSERT INTO instituicao (nome) values ("UFPR - Universidade Federal do Paraná");
INSERT INTO instituicao (nome) values ("UNILA - Universidade Federal da Integração Latino Americana");
INSERT INTO instituicao (nome) values ("UFFS - Universidade Federal da Fronteira do Sul");
INSERT INTO instituicao (nome) values ("FAE - FAE Centro Universitário");
INSERT INTO instituicao (nome) values ("FAG - Fundação Assis Gurgacz");
INSERT INTO instituicao (nome) values ("FEPAR - Faculdade Evangélica do Paraná");
INSERT INTO instituicao (nome) values ("FPP - Faculdades Pequeno Príncipe");
INSERT INTO instituicao (nome) values ("FTSA - Faculdade Teológica Sul Americana");
INSERT INTO instituicao (nome) values ("PUCPR - Pontifícia Universidade Católica do Paraná");
INSERT INTO instituicao (nome) values ("UNIFIL - Centro Universitário Filadélfia");
INSERT INTO instituicao (nome) values ("Univel - União Educacional de Cascavel");
INSERT INTO instituicao (nome) values ("UNINGÁ - Faculdade Ingá");
INSERT INTO instituicao (nome) values ("CAMPO REAL - Faculdade Campo Real");
INSERT INTO instituicao (nome) values ("CESCAGE - Centro de Ensino Superior dos Campos Gerais");
INSERT INTO instituicao (nome) values ("CESUFOZ - Centro de Ensino Superior de Foz do Iguaçu");
INSERT INTO instituicao (nome) values ("CESUMAR - Centro Universitário de Maringá");
INSERT INTO instituicao (nome) values ("FAAB - Faculdade Alfa Brasil");
INSERT INTO instituicao (nome) values ("FAC - Faculdade Curitibana");
INSERT INTO instituicao (nome) values ("FAFIG - Faculdade de Foz do Iguaçu");
INSERT INTO instituicao (nome) values ("FAG - Faculdade Guairacá");
INSERT INTO instituicao (nome) values ("FAJAR - Faculdade Jaguariaíva");
INSERT INTO instituicao (nome) values ("FATEB - Faculdade de Telêmaco Borba");
INSERT INTO instituicao (nome) values ("FANP - Faculdade do Noroeste Paranaense");
INSERT INTO instituicao (nome) values ("FAPAR - Faculdade Paranaense");
INSERT INTO instituicao (nome) values ("FAPI - Faculdades de Pinhais");
INSERT INTO instituicao (nome) values ("FASF - Faculdade Sagrada Família");
INSERT INTO instituicao (nome) values ("FARESC - Faculdades Integradas Santa Cruz de Curitiba");
INSERT INTO instituicao (nome) values ("FEITEP - Faculdade de Engenharia e Inovação Técnico Profissional");
INSERT INTO instituicao (nome) values ("FESC - Fundação de Ensino Superior de Clevelândia");
INSERT INTO instituicao (nome) values ("FG - Faculdade Guarapuava");
INSERT INTO instituicao (nome) values ("FIES - Faculdades Integradas Espírita");
INSERT INTO instituicao (nome) values ("FML - Faculdade Metropolitana Londrinense");
INSERT INTO instituicao (nome) values ("OPET - Organização Paranaense de Ensino Técnico");
INSERT INTO instituicao (nome) values ("SECAL - Faculdade Santa Amélia");
INSERT INTO instituicao (nome) values ("UDC - Centro Universitário União Dinâmica das Cataratas");
INSERT INTO instituicao (nome) values ("UEB - Universidade Eletrônica do Brasil");
INSERT INTO instituicao (nome) values ("UNIANDRADE - Centro Universitário Campos de Andrade");
INSERT INTO instituicao (nome) values ("UNICAMPO - Faculdade União de Campo Mourão");
INSERT INTO instituicao (nome) values ("UNICURITIBA - Centro Universitário Curitiba");
INSERT INTO instituicao (nome) values ("UNINTER - Grupo Educacional Uninter");
INSERT INTO instituicao (nome) values ("UNIPAR - Universidade Paranaense");
INSERT INTO instituicao (nome) values ("UNOPAR - Universidade do Norte do Paraná");
INSERT INTO instituicao (nome) values ("UCP - Faculdades do Centro do Paraná");
INSERT INTO instituicao (nome) values ("UP - Universidade Positivo");
INSERT INTO instituicao (nome) values ("UTP - Universidade Tuiuti do Paraná");
INSERT INTO instituicao (nome) values ("UNISEP - União de Ensino do Sudoeste do Paraná");
INSERT INTO instituicao (nome) values ("UFPI - Universidade Federal do Piauí");
INSERT INTO instituicao (nome) values ("IFPI - Instituto Federal do Piauí");
INSERT INTO instituicao (nome) values ("UNIVASF - Universidade Federal do Vale do São Francisco");
INSERT INTO instituicao (nome) values ("UFPDra - Universidade Federal do Delta do Parnaíba");
INSERT INTO instituicao (nome) values ("UESPI - Universidade Estadual do Piauí");
INSERT INTO instituicao (nome) values ("ISEAF - Instituto Superior de Educação Antonino Freire");
INSERT INTO instituicao (nome) values ("AESPI - Associação de Ensino Superior do Piauí");
INSERT INTO instituicao (nome) values ("ALIANÇA - Faculdade Aliança");
INSERT INTO instituicao (nome) values ("CET - Centro de Educação Tecnológico");
INSERT INTO instituicao (nome) values ("CEUT - Centro de Ensino Unificado de Teresina");
INSERT INTO instituicao (nome) values ("FACID - Faculdade Integral Diferencial");
INSERT INTO instituicao (nome) values ("FAP - Faculdade Piauiense");
INSERT INTO instituicao (nome) values ("FAPI - Faculdade do Piauí");
INSERT INTO instituicao (nome) values ("FSA - Faculdade Santo Agostinho");
INSERT INTO instituicao (nome) values ("ICF - Instituto Camillo Filho");
INSERT INTO instituicao (nome) values ("IERSA - Instituto Educacional Raimundo Sá (Faculdade Raimundo Sá)");
INSERT INTO instituicao (nome) values ("Novafapi - Faculdade de Saúde, Ciências Humanas e Tecnológicas do Piauí");
INSERT INTO instituicao (nome) values ("NovaUnesc - Faculdade Nova Unesc");
INSERT INTO instituicao (nome) values ("FeMASS - Faculdade Professor Miguel  ngelo da Silva Santos - Macaé");
INSERT INTO instituicao (nome) values ("ISERJ- Instituto Superior de Educação do Rio de Janeiro");
INSERT INTO instituicao (nome) values ("FAETERJ - Faculdade de Educação Tecnológica do Estado do Rio de Janeiro");
INSERT INTO instituicao (nome) values ("UENF - Universidade Estadual do Norte Fluminense");
INSERT INTO instituicao (nome) values ("UERJ - Universidade do Estado do Rio de Janeiro");
INSERT INTO instituicao (nome) values ("UEZO - Universidade Estadual da Zona Oeste");
INSERT INTO instituicao (nome) values ("IFF - Instituto Federal Fluminense");
INSERT INTO instituicao (nome) values ("IFRJ - Instituto Federal do Rio de Janeiro");
INSERT INTO instituicao (nome) values ("CEFET/RJ - Centro Federal de Educação Tecnológica Celso Suckow da Fonseca");
INSERT INTO instituicao (nome) values ("ENCE - Escola Nacional de Ciências Estatísticas");
INSERT INTO instituicao (nome) values ("UFF - Universidade Federal Fluminense");
INSERT INTO instituicao (nome) values ("UFRJ - Universidade Federal do Rio de Janeiro");
INSERT INTO instituicao (nome) values ("UFRRJ - Universidade Federal Rural do Rio de Janeiro");
INSERT INTO instituicao (nome) values ("UNIRIO - Universidade Federal do Estado do Rio de Janeiro");
INSERT INTO instituicao (nome) values ("ABMDP II - Academia de Bombeiro Militar Dom Pedro II");
INSERT INTO instituicao (nome) values ("AMAN - Academia Militar de Agulhas Negras");
INSERT INTO instituicao (nome) values ("APMDJVI - Academia de Polícia Militar Dom João VI");
INSERT INTO instituicao (nome) values ("CIAGA - Centro de Instrução Almirante Graça Aranha");
INSERT INTO instituicao (nome) values ("EN - Escola Naval");
INSERT INTO instituicao (nome) values ("IME - Instituto Militar de Engenharia");
INSERT INTO instituicao (nome) values ("MACKENZIE-RIO - Faculdade Presbiteriana Mackenzie Rio");
INSERT INTO instituicao (nome) values ("IBMEC - Instituto Brasileiro de Mercado e Capitais");
INSERT INTO instituicao (nome) values ("FGV - Fundação Getulio Vargas");
INSERT INTO instituicao (nome) values ("ESPM-RIO - Escola Superior de Propaganda e Marketing");
INSERT INTO instituicao (nome) values ("PUC-RIO - Pontifícia Universidade Católica do Rio de Janeiro");
INSERT INTO instituicao (nome) values ("UNIGRANRIO - Universidade do Grande Rio");
INSERT INTO instituicao (nome) values ("CELSO LISBOA - Centro Universitário Celso Lisboa");
INSERT INTO instituicao (nome) values ("FUNENSEG - Escola Nacional de Seguros");
INSERT INTO instituicao (nome) values ("FIJ - Faculdades Integradas de Jacarepaguá");
INSERT INTO instituicao (nome) values ("FACHA - Faculdades Integradas Hélio Alonso");
INSERT INTO instituicao (nome) values ("FFSD - Faculdade de Filosofia Santa Doroteia");
INSERT INTO instituicao (nome) values ("FMC - Faculdade de Medicina de Campos");
INSERT INTO instituicao (nome) values ("FSMA - Faculdade Salesiana de Macaé");
INSERT INTO instituicao (nome) values ("FTESM - Fundação Técnico Educacional Souza Marques");
INSERT INTO instituicao (nome) values ("FSB/RJ - Faculdade de São Bento do Rio de Janeiro");
INSERT INTO instituicao (nome) values ("UCAM - Universidade Cândido Mendes");
INSERT INTO instituicao (nome) values ("IBMR - Centro Universitário IBMR");
INSERT INTO instituicao (nome) values ("UCB - Universidade Castelo Branco");
INSERT INTO instituicao (nome) values ("UCP - Universidade Católica de Petrópolis");
INSERT INTO instituicao (nome) values ("UGB - Centro Universitário Geraldo Di Biase");
INSERT INTO instituicao (nome) values ("UGS - Universidade Gama e Souza");
INSERT INTO instituicao (nome) values ("UNISUAM - Centro Universitário Augusto Motta");
INSERT INTO instituicao (nome) values ("UNIABEU - UNIABEU Centro Universitário");
INSERT INTO instituicao (nome) values ("UNICARIOCA - Centro Universitário Carioca");
INSERT INTO instituicao (nome) values ("UNIFESO - Centro Universitário Serra dos Órgãos");
INSERT INTO instituicao (nome) values ("UNIVERSO - Universidade Salgado de Oliveira");
INSERT INTO instituicao (nome) values ("USS - Universidade Severino Sombra");
INSERT INTO instituicao (nome) values ("USU - Universidade Santa Úrsula");
INSERT INTO instituicao (nome) values ("UVA - Universidade Veiga de Almeida");
INSERT INTO instituicao (nome) values ("REDENTOR - Sociedade Universitária Redentor (Faculdade Redentor)");
INSERT INTO instituicao (nome) values ("UNIVERITAS - Centro Universitário Universus Veritas");
INSERT INTO instituicao (nome) values ("INFNET - Instituto Infnet");
INSERT INTO instituicao (nome) values ("SENAC - Faculdade Senac Rio de Janeiro");
INSERT INTO instituicao (nome) values ("UBM - Centro Universitário de Barra Mansa");
INSERT INTO instituicao (nome) values ("UNESA - Universidade Estácio de Sá");
INSERT INTO instituicao (nome) values ("UNIFOA - Centro Universitário de Volta Redonda");
INSERT INTO instituicao (nome) values ("UERN - Universidade do Estado do Rio Grande do Norte");
INSERT INTO instituicao (nome) values ("IFRN - Instituto Federal do Rio Grande do Norte");
INSERT INTO instituicao (nome) values ("UFERSA - Universidade Federal Rural do Semi-Árido");
INSERT INTO instituicao (nome) values ("UFRN - Universidade Federal do Rio Grande do Norte");
INSERT INTO instituicao (nome) values ("ULBRA - Universidade Luterana do Brasil (Polo Natal)");
INSERT INTO instituicao (nome) values ("UNP - Universidade Potiguar");
INSERT INTO instituicao (nome) values ("FARN - Faculdade Natalense para o Desenvolvimento do Rio Grande do Norte");
INSERT INTO instituicao (nome) values ("Fatern Gama Filho - Faculdade de Excelência do Rio Grande do Norte");
INSERT INTO instituicao (nome) values ("FAL - Faculdade de Natal");
INSERT INTO instituicao (nome) values ("Facex - Faculdade de Ciências, Cultura e Extensão do RN");
INSERT INTO instituicao (nome) values ("FCC - Faculdade Câmara Cascudo");
INSERT INTO instituicao (nome) values ("Fanec - Faculdade Natalense de Ensino e Cultura");
INSERT INTO instituicao (nome) values ("FCNSN - Faculdade Católica Nossa Senhora Das Neves");
INSERT INTO instituicao (nome) values ("UNOPAR - Universidade Norte do Paraná (Polo Natal)");
INSERT INTO instituicao (nome) values ("UNINASSAU - Faculdade Maurício de Nassau - (Pólo Natal)");
INSERT INTO instituicao (nome) values ("IPOG - Instituto de Pós-Graduação (Pólo Natal)");
INSERT INTO instituicao (nome) values ("Facene/RN - Faculdade de Enfermagem e Medicina Nova Esperança de Mossoró");
INSERT INTO instituicao (nome) values ("Mater Christi - Faculdade Mater Christi");
INSERT INTO instituicao (nome) values ("UERGS - Universidade Estadual do Rio Grande do Sul");
INSERT INTO instituicao (nome) values ("FURG - Universidade Federal do Rio Grande");
INSERT INTO instituicao (nome) values ("IFFarroupilha - Instituto Federal Farroupilha");
INSERT INTO instituicao (nome) values ("IFRS - Instituto Federal do Rio Grande do Sul");
INSERT INTO instituicao (nome) values ("IFSul - Instituto Federal Sul-rio-grandense");
INSERT INTO instituicao (nome) values ("UFCSPA - Universidade Federal de Ciências da Saúde de Porto Alegre");
INSERT INTO instituicao (nome) values ("UFPEL - Universidade Federal de Pelotas");
INSERT INTO instituicao (nome) values ("UFRGS - Universidade Federal do Rio Grande do Sul");
INSERT INTO instituicao (nome) values ("UFSM - Universidade Federal de Santa Maria");
INSERT INTO instituicao (nome) values ("UNIPAMPA - Universidade Federal do Pampa");
INSERT INTO instituicao (nome) values ("UFFS - Universidade Federal da Fronteira do Sul");
INSERT INTO instituicao (nome) values ("CNECSAN - Faculdade CNEC Santo  ngelo");
INSERT INTO instituicao (nome) values ("FACCAT - Faculdades de Taquara");
INSERT INTO instituicao (nome) values ("FACOS - Faculdade Cenecista de Osório");
INSERT INTO instituicao (nome) values ("FISMA - Faculdade Integrada de Santa Maria");
INSERT INTO instituicao (nome) values ("FAPA - Faculdade Porto-Alegrense");
INSERT INTO instituicao (nome) values ("FEEVALE - Universidade Feevale");
INSERT INTO instituicao (nome) values ("FACENSA - Faculdade Cenecista Nossa Senhora dos Anjos");
INSERT INTO instituicao (nome) values ("IACS - Instituto Adventista Cruzeiro do Sul");
INSERT INTO instituicao (nome) values ("MARQUÊS - Instituto de Educação Cenecista Marquês de Herval");
INSERT INTO instituicao (nome) values ("IPA - Centro Universitário Metodista do Instituto Porto Alegre");
INSERT INTO instituicao (nome) values ("PUCRS - Pontifícia Universidade Católica do Rio Grande do Sul");
INSERT INTO instituicao (nome) values ("UCPEL - Universidade Católica de Pelotas");
INSERT INTO instituicao (nome) values ("UCS - Universidade de Caxias do Sul");
INSERT INTO instituicao (nome) values ("ULBRA - Universidade Luterana do Brasil");
INSERT INTO instituicao (nome) values ("UNICRUZ - Universidade de Cruz Alta");
INSERT INTO instituicao (nome) values ("UFN - Universidade Franciscana");
INSERT INTO instituicao (nome) values ("UNIJUÍ - Universidade Regional do Noroeste do Estado do Rio Grande do Sul");
INSERT INTO instituicao (nome) values ("UNIRITTER - Centro Universitário Ritter dos Reis");
INSERT INTO instituicao (nome) values ("UNILASALLE-RJ - Universidade La Salle - RJ");
INSERT INTO instituicao (nome) values ("UNISC - Universidade de Santa Cruz do Sul");
INSERT INTO instituicao (nome) values ("UNISINOS - Universidade do Vale do Rio dos Sinos");
INSERT INTO instituicao (nome) values ("UNIVATES - Centro Universitário UNIVATES");
INSERT INTO instituicao (nome) values ("UPF - Universidade de Passo Fundo");
INSERT INTO instituicao (nome) values ("URCAMP - Universidade da Região da Campanha");
INSERT INTO instituicao (nome) values ("URI - Universidade Regional Integrada do Alto Uruguai e das Missões");
INSERT INTO instituicao (nome) values ("EST - Faculdades EST");
INSERT INTO instituicao (nome) values ("CESF - Centro de Ensino Superior Cenecista de Farroupilha");
INSERT INTO instituicao (nome) values ("CASTELLI - Escola Superior de Hotelaria Castelli");
INSERT INTO instituicao (nome) values ("ESMARGS - Escola Superior de Música e Artes do Rio Grande do Sul");
INSERT INTO instituicao (nome) values ("FAE - Faculdade Anglicana de Erechim");
INSERT INTO instituicao (nome) values ("FAE - Faculdades Equipe - Sapucaia do Sul");
INSERT INTO instituicao (nome) values ("FAM - Faculdade Antonio Meneghetti");
INSERT INTO instituicao (nome) values ("FSG - Faculdade da Serra Gaúcha");
INSERT INTO instituicao (nome) values ("FTEC - Faculdade de Tecnologia TecBrasil");
INSERT INTO instituicao (nome) values ("IDEAU - Instituto de Desenvolvimento Educacional do Alto Uruguai - Getúlio Vargas");
INSERT INTO instituicao (nome) values ("SENAC - Faculdade Senac - Rio Grande do Sul");
INSERT INTO instituicao (nome) values ("SJT - Instituição Educacional São Judas Tadeu");
INSERT INTO instituicao (nome) values ("UNIANHANGUERA - Anhanguera Educacional S.A.");
INSERT INTO instituicao (nome) values ("UNIRITTER - Centro Universitário Ritter dos Reis");
INSERT INTO instituicao (nome) values ("FEMA - Escola Técnica e Superior Machado de Assis - Santa Rosa");
INSERT INTO instituicao (nome) values ("FADISMA - Faculdade de Direito de Santa Maria");
INSERT INTO instituicao (nome) values ("FAACS - Faculdade Anglo-Americano de Caxias do Sul - Grupo Educacional");
INSERT INTO instituicao (nome) values ("UNIR - Universidade Federal de Rondônia");
INSERT INTO instituicao (nome) values ("IFRO - Instituto Federal de Rondônia");
INSERT INTO instituicao (nome) values ("AVEC - Associação Vilhenense de Educação e Cultura");
INSERT INTO instituicao (nome) values ("CEULJI/ULBRA - Centro Universitário Luterano de Ji-Paraná");
INSERT INTO instituicao (nome) values ("ILES/ULBRA - Instituto Luterano de Ensino Superior de Porto Velho");
INSERT INTO instituicao (nome) values ("FAMA - Faculdade da Amazônia");
INSERT INTO instituicao (nome) values ("FAEV/UNESC - Faculdade de Educação e Cultura de Vilhena");
INSERT INTO instituicao (nome) values ("FARO - Faculdade de Ciências Humanas, Exatas e Letras de Rondônia");
INSERT INTO instituicao (nome) values ("UNIRON - Faculdade Interamericana de Porto Velho");
INSERT INTO instituicao (nome) values ("FIMCA - Faculdades Integradas Aparício Carvalho");
INSERT INTO instituicao (nome) values ("FSL - Faculdade São Lucas");
INSERT INTO instituicao (nome) values ("FIAR - Faculdades Integradas de Ariquemes");
INSERT INTO instituicao (nome) values ("FAAR - Faculdades Associadas de Ariquemes");
INSERT INTO instituicao (nome) values ("FAEMA - Faculdade de Educação e Meio Ambiente");
INSERT INTO instituicao (nome) values ("FACIMED - Faculdade de Ciências Biomédicas de Cacoal");
INSERT INTO instituicao (nome) values ("UNESC - Faculdades Integradas de Cacoal");
INSERT INTO instituicao (nome) values ("UNIJIPA - Faculdade Panamericana de Ji-Paraná");
INSERT INTO instituicao (nome) values ("CLARETIANO - centro universitário");
INSERT INTO instituicao (nome) values ("Funorte - Faculdades Unidas do Norte de Minas");
INSERT INTO instituicao (nome) values ("UNOPAR - universidade á distancia do norte do Paraná");
INSERT INTO instituicao (nome) values ("UNIP - Universidade Paulista");
INSERT INTO instituicao (nome) values ("UERR - Universidade Estadual de Roraima");
INSERT INTO instituicao (nome) values ("UFRR - Universidade Federal de Roraima");
INSERT INTO instituicao (nome) values ("IFRR - Instituto Federal de Roraima");
INSERT INTO instituicao (nome) values ("Estácio - Estácio");
INSERT INTO instituicao (nome) values ("FACETEN - Faculdade de Ciências, Educação e Teologia do Norte do Brasil");
INSERT INTO instituicao (nome) values ("Cathedral - Faculdades Cathedral");
INSERT INTO instituicao (nome) values ("FARES - Faculdade Roraimense de Ensino Superior");
INSERT INTO instituicao (nome) values ("Municipais - constituídas sob a forma de Fundações");
INSERT INTO instituicao (nome) values ("FURB - Fundação Universidade Regional de Blumenau");
INSERT INTO instituicao (nome) values ("SOCIESC - Sociedade Educacional de Santa Catarina");
INSERT INTO instituicao (nome) values ("UNESC - Universidade do Extremo Sul Catarinense");
INSERT INTO instituicao (nome) values ("USJ - Universidade Municipal de São José");
INSERT INTO instituicao (nome) values ("FMP - Faculdade Municipal de Palhoça");
INSERT INTO instituicao (nome) values ("UDESC - Universidade do Estado de Santa Catarina");
INSERT INTO instituicao (nome) values ("UFFS - Universidade Federal da Fronteira Sul");
INSERT INTO instituicao (nome) values ("IFSC - Instituto Federal de Santa Catarina");
INSERT INTO instituicao (nome) values ("IFC - Instituto Federal Catarinense");
INSERT INTO instituicao (nome) values ("UFSC - Universidade Federal de Santa Catarina");
INSERT INTO instituicao (nome) values ("ACE - Associação Catarinense de Ensino");
INSERT INTO instituicao (nome) values ("FACC - Faculdade Concórdia");
INSERT INTO instituicao (nome) values ("FAACH - Faculdade Santa Rita de Chapecó");
INSERT INTO instituicao (nome) values ("FAP - Faculdade Santa Rita Palmitos");
INSERT INTO instituicao (nome) values ("SENAC - Faculdade Senac - Santa Catarina");
INSERT INTO instituicao (nome) values ("UNOESC - Universidade do Oeste de Santa Catarina");
INSERT INTO instituicao (nome) values ("UNIASSELVI - Centro Universitário Leonardo da Vinci");
INSERT INTO instituicao (nome) values ("UNIBAVE - Universidade Barriga Verde");
INSERT INTO instituicao (nome) values ("UNIFEBE - Centro Universitário de Brusque");
INSERT INTO instituicao (nome) values ("UNISUL - Universidade do Sul de Santa Catarina");
INSERT INTO instituicao (nome) values ("UNC - Universidade do Contestado");
INSERT INTO instituicao (nome) values ("UNIARP - Universidade Alto Vale do Rio do Peixe");
INSERT INTO instituicao (nome) values ("UNERJ - Centro Universitário de Jaraguá do Sul");
INSERT INTO instituicao (nome) values ("UNIVALI - Universidade do Vale do Itajaí");
INSERT INTO instituicao (nome) values ("UNIVILLE - Universidade da Região de Joinville");
INSERT INTO instituicao (nome) values ("UNOCHAPECÓ - Universidade Comunitária Regional de Chapecó");
INSERT INTO instituicao (nome) values ("UNIPLAC - Universidade do Planalto Catarinense");
INSERT INTO instituicao (nome) values ("UNISUL - Universidade do Sul de Santa Catarina");
INSERT INTO instituicao (nome) values ("UNITAU - Universidade de Taubaté");
INSERT INTO instituicao (nome) values ("USCS - Universidade Municipal de São Caetano do Sul");
INSERT INTO instituicao (nome) values ("USP - Universidade de São Paulo");
INSERT INTO instituicao (nome) values ("UNICAMP - Universidade Estadual de Campinas");
INSERT INTO instituicao (nome) values ("UNESP - Universidade Estadual Paulista");
INSERT INTO instituicao (nome) values ("UNIVESP - Universidade Virtual do Estado de São Paulo");
INSERT INTO instituicao (nome) values ("FAMEMA - Faculdade de Medicina de Marília");
INSERT INTO instituicao (nome) values ("FAMERP - Faculdade de Medicina de São José do Rio Preto");
INSERT INTO instituicao (nome) values ("FATEC - Faculdade de Tecnologia do Estado de São Paulo");
INSERT INTO instituicao (nome) values ("APMBB - Academia de Polícia Militar do Barro Branco");
INSERT INTO instituicao (nome) values ("UFSCar - Universidade Federal de São Carlos");
INSERT INTO instituicao (nome) values ("UNIFESP - Universidade Federal de São Paulo");
INSERT INTO instituicao (nome) values ("UFABC - Universidade Federal do ABC");
INSERT INTO instituicao (nome) values ("IFSP - Instituto Federal de Educação, Ciência e Tecnologia de São Paulo");
INSERT INTO instituicao (nome) values ("ITA - Instituto Tecnológico de Aeronáutica");
INSERT INTO instituicao (nome) values ("AFA - Academia da Força Aérea");
INSERT INTO instituicao (nome) values ("Uni-FACEF (Centro Universitário Municipal de Franca)");
INSERT INTO instituicao (nome) values ("UNIFAE - Centro Universitário das Faculdades Associadas de Ensino");
INSERT INTO instituicao (nome) values ("Uni-FACEF - Centro Universitário de Franca");
INSERT INTO instituicao (nome) values ("CUFSA - Centro Universitário Fundação Santo André");
INSERT INTO instituicao (nome) values ("FACCAMP - Faculdade de Campo Limpo Paulista");
INSERT INTO instituicao (nome) values ("EEP/FUMEP - Escola de Engenharia de Piracicaba");
INSERT INTO instituicao (nome) values ("ESEFJ - Escola Superior de Educação Física de Jundiaí");
INSERT INTO instituicao (nome) values ("FITO - Fundação Instituto Tecnológico de Osasco");
INSERT INTO instituicao (nome) values ("FATEB - Faculdade de Ciências e Tecnologia de Birigui");
INSERT INTO instituicao (nome) values ("FDF - Faculdade de Direito de Franca");
INSERT INTO instituicao (nome) values ("FDSBC - Faculdade de Direito de São Bernardo do Campo");
INSERT INTO instituicao (nome) values ("FAIBI - Faculdade de Filosofia, Ciências e Letras de Ibitinga");
INSERT INTO instituicao (nome) values ("FFCL - Faculdade de Filosofia Ciências e Letras de São José do Rio Pardo");
INSERT INTO instituicao (nome) values ("FMABC - Faculdade de Medicina do ABC");
INSERT INTO instituicao (nome) values ("FMJ - Faculdade de Medicina de Jundiaí");
INSERT INTO instituicao (nome) values ("FMPFM - Faculdade Municipal Professor Franco Montoro de Mogi Guaçu");
INSERT INTO instituicao (nome) values ("FAI - Faculdades Adamantinenses Integradas");
INSERT INTO instituicao (nome) values ("FAFEM - Faculdades da Fundação de Ensino de Mococa");
INSERT INTO instituicao (nome) values ("FUNEC - Faculdades Integradas de Santa Fé do Sul");
INSERT INTO instituicao (nome) values ("IESF - Instituto de Ensino Superior da Fupesp");
INSERT INTO instituicao (nome) values ("IMMES - Instituto Matonense Municipal de Ensino Superior");
INSERT INTO instituicao (nome) values ("IMESB - Instituto Municipal de Ensino Superior de Bebedouro Victório Cardassi");
INSERT INTO instituicao (nome) values ("IMES Catanduva - Instituto Municipal de Ensino Superior de Catanduva");
INSERT INTO instituicao (nome) values ("IMESSM - Instituto Municipal de Ensino Superior de São Manuel");
INSERT INTO instituicao (nome) values ("IMESA - Instituto Municipal de Ensino Superior de Assis");
INSERT INTO instituicao (nome) values ("FEA - Fundação Educacional Araçatuba");
INSERT INTO instituicao (nome) values ("MACK - Universidade Presbiteriana Mackenzie");
INSERT INTO instituicao (nome) values ("PUCSP - Pontifícia Universidade Católica de São Paulo");
INSERT INTO instituicao (nome) values ("PUC-Campinas - Pontifícia Universidade Católica de Campinas");
INSERT INTO instituicao (nome) values ("UMESP - Universidade Metodista de São Paulo");
INSERT INTO instituicao (nome) values ("UNAERP - Universidade de Ribeirão Preto");
INSERT INTO instituicao (nome) values ("UNIMEP - Universidade Metodista de Piracicaba");
INSERT INTO instituicao (nome) values ("UNISANTOS - Universidade Católica de Santos");
INSERT INTO instituicao (nome) values ("UNICASTELO - Universidade Camilo Castelo Branco");
INSERT INTO instituicao (nome) values ("UNISA - Universidade de Santo Amaro");
INSERT INTO instituicao (nome) values ("UNIVAP - Universidade do Vale do Paraíba");
INSERT INTO instituicao (nome) values ("UNOESTE - Universidade do Oeste Paulista");
INSERT INTO instituicao (nome) values ("USF - Universidade São Francisco");
INSERT INTO instituicao (nome) values ("CBM - Centro Universitário Barão de Mauá");
INSERT INTO instituicao (nome) values ("UNISALESIANO - Centro Universitário Católico Salesiano Auxilium");
INSERT INTO instituicao (nome) values ("CUSC - Centro Universitário São Camilo");
INSERT INTO instituicao (nome) values ("FEBASP - Centro Universitário Belas Artes de São Paulo");
INSERT INTO instituicao (nome) values ("FEI - Centro Universitário FEI");
INSERT INTO instituicao (nome) values ("FMU - Centro Universitário das Faculdades Metropolitanas Unidas");
INSERT INTO instituicao (nome) values ("SENAC - Centro Universitário Senac - São Paulo");
INSERT INTO instituicao (nome) values ("UNASP - Centro Universitário Adventista de São Paulo");
INSERT INTO instituicao (nome) values ("UNIARA - Universidade de Araraquara");
INSERT INTO instituicao (nome) values ("UNICEP - Centro Universitário Central Paulista");
INSERT INTO instituicao (nome) values ("UNIFAI - Centro Universitário Assunção");
INSERT INTO instituicao (nome) values ("UNIFEB - Centro Universitário da Fundação Educacional de Barretos");
INSERT INTO instituicao (nome) values ("UNIFEOB - Centro Universitário Octávio Bastos");
INSERT INTO instituicao (nome) values ("UNIFIEO - Centro Universitário FIEO");
INSERT INTO instituicao (nome) values ("UNILAGO - União das Faculdades dos Grandes Lagos");
INSERT INTO instituicao (nome) values ("UNIMONTE - Centro Universitário Monte Serrat");
INSERT INTO instituicao (nome) values ("UNISAL - Centro Universitário Salesiano de São Paulo");
INSERT INTO instituicao (nome) values ("UNORP - Centro Universitário do Norte Paulista");
INSERT INTO instituicao (nome) values ("UNIRP - Centro Universitário de Rio Preto");
INSERT INTO instituicao (nome) values ("UNIVEM - Centro Universitário Eurípedes de Marília");
INSERT INTO instituicao (nome) values ("BSP - Business School São Paulo");
INSERT INTO instituicao (nome) values ("FGV - Fundação Getúlio Vargas");
INSERT INTO instituicao (nome) values ("FATEC - Faculdade de Teologia e Ciências");
INSERT INTO instituicao (nome) values ("FECAP - Fundação Escola de Comércio Álvares Penteado");
INSERT INTO instituicao (nome) values ("ESPM - Escola Superior de Propaganda e Marketing");
INSERT INTO instituicao (nome) values ("ESAGS - Escola Superior de Administração e Gestão");
INSERT INTO instituicao (nome) values ("IMT - Instituto Mauá de Tecnologia");
INSERT INTO instituicao (nome) values ("FCL - Faculdade Cásper Líbero");
INSERT INTO instituicao (nome) values ("FAAP - Fundação Armando Álvares Penteado");
INSERT INTO instituicao (nome) values ("Insper - Instituto de Ensino e Pesquisa");
INSERT INTO instituicao (nome) values ("IMT - Instituto Mauá de Tecnologia");
INSERT INTO instituicao (nome) values ("FESPSP - Fundação Escola de Sociologia e Política de São Paulo");
INSERT INTO instituicao (nome) values ("FRB - Faculdades Integradas Rio Branco");
INSERT INTO instituicao (nome) values ("DOMPEDRO - Faculdades Integradas Dom Pedro II");
INSERT INTO instituicao (nome) values ("FIO - Faculdades Integradas de Ourinhos");
INSERT INTO instituicao (nome) values ("FIRB - Faculdades Integradas Rio Branco");
INSERT INTO instituicao (nome) values ("FTML - Faculdade de Teologia Metodista Livre");
INSERT INTO instituicao (nome) values ("FTT - Faculdade de Tecnologia Termomecânica");
INSERT INTO instituicao (nome) values ("FAPCOM - Faculdade Paulus de Comunicação e Tecnologia");
INSERT INTO instituicao (nome) values ("UCESP - Faculdade União Cultural do Estado de São Paulo");
INSERT INTO instituicao (nome) values ("UniSãopaulo - Instituto São Paulo de Formação e Especialização Profissional");
INSERT INTO instituicao (nome) values ("FAZP - Faculdade Zumbi dos Palmares");
INSERT INTO instituicao (nome) values ("FEF - Fundação Educacional de Fernandópolis");
INSERT INTO instituicao (nome) values ("FCMSCSP - Faculdade de Ciências Médicas da Santa Casa de São Paulo");
INSERT INTO instituicao (nome) values ("UNINOVE - Campus Memorial - São Paulo/SP");
INSERT INTO instituicao (nome) values ("Universidade Paulista - Campus Paraíso - São Paulo/SP");
INSERT INTO instituicao (nome) values ("CEUNSP - Centro Universitário Nossa Senhora do Patrocínio");
INSERT INTO instituicao (nome) values ("FCDA - Faculdade Drummond");
INSERT INTO instituicao (nome) values ("ITE - Centro Universitário de Bauru");
INSERT INTO instituicao (nome) values ("UAM - Universidade Anhembi Morumbi");
INSERT INTO instituicao (nome) values ("UBC - Universidade Braz Cubas");
INSERT INTO instituicao (nome) values ("UMC - Universidade de Mogi das Cruzes");
INSERT INTO instituicao (nome) values ("UNG - Universidade Guarulhos");
INSERT INTO instituicao (nome) values ("UniABC - Universidade do Grande ABC");
INSERT INTO instituicao (nome) values ("UNIBAN - Universidade Bandeirante de São Paulo");
INSERT INTO instituicao (nome) values ("UNIBERO - Centro Universitário Anhanguera de São Paulo");
INSERT INTO instituicao (nome) values ("UNICSUL - Universidade Cruzeiro do Sul");
INSERT INTO instituicao (nome) values ("UNISEB - Centro Universitário Estácio UniSEB -São Paulo");
INSERT INTO instituicao (nome) values ("UNIFRAN - Universidade de Franca");
INSERT INTO instituicao (nome) values ("UNIMAR - Universidade de Marília");
INSERT INTO instituicao (nome) values ("UNINOVE - Universidade Nove de Julho");
INSERT INTO instituicao (nome) values ("UNIP - Universidade Paulista");
INSERT INTO instituicao (nome) values ("UNIMES - Universidade Metropolitana de Santos");
INSERT INTO instituicao (nome) values ("UNISANTA - Universidade Santa Cecília");
INSERT INTO instituicao (nome) values ("UNISO - Universidade de Sorocaba");
INSERT INTO instituicao (nome) values ("USJT - Universidade São Judas Tadeu");
INSERT INTO instituicao (nome) values ("AESA - Anhanguera Educacional");
INSERT INTO instituicao (nome) values ("FACAMP - Faculdades de Campinas");
INSERT INTO instituicao (nome) values ("FACIC - Faculdade de Ciências Humanas de Cruzeiro");
INSERT INTO instituicao (nome) values ("FACMIL - Faculdade de Administração de São José do Rio Preto");
INSERT INTO instituicao (nome) values ("FADI - Faculdade de Direito de Sorocaba");
INSERT INTO instituicao (nome) values ("FADISC - Faculdades Integradas de São Carlos");
INSERT INTO instituicao (nome) values ("FALS - Faculdade do Litoral Sul Paulista");
INSERT INTO instituicao (nome) values ("FAM - Faculdade de Americana");
INSERT INTO instituicao (nome) values ("FIAP - Faculdade de Informática e Administração Paulista");
INSERT INTO instituicao (nome) values ("FIRB - Faculdades Integradas Rio Branco");
INSERT INTO instituicao (nome) values ("FIT - Faculdade Impacta Tecnologia");
INSERT INTO instituicao (nome) values ("FMS - Faculdade Mario Schenberg");
INSERT INTO instituicao (nome) values ("FNC - Faculdade Nossa Cidade");
INSERT INTO instituicao (nome) values ("FOC - Faculdades Oswaldo Cruz");
INSERT INTO instituicao (nome) values ("ISES - Faculdade Sumaré");
INSERT INTO instituicao (nome) values ("JAPI - Faculdade Japi");
INSERT INTO instituicao (nome) values ("SLMANDIC - Faculdade de Odontologia e Centro de Pesquisas Odontológicas São Leopoldo Mandic");
INSERT INTO instituicao (nome) values ("TECMED - Faculdade de Tecnologia Tecmed");
INSERT INTO instituicao (nome) values ("BANDTEC - Faculdade de Tecnologia Bandeirantes");
INSERT INTO instituicao (nome) values ("FLAMINGO - Faculdade Flamingo");
INSERT INTO instituicao (nome) values ("UFS - Universidade Federal de Sergipe");
INSERT INTO instituicao (nome) values ("IFS - Instituto Federal de Sergipe");
INSERT INTO instituicao (nome) values ("Unit - Universidade Tiradentes");
INSERT INTO instituicao (nome) values ("FPD - Faculdade Pio Décimo");
INSERT INTO instituicao (nome) values ("ESTÁCIO - Faculdade Estácio de Sergipe");
INSERT INTO instituicao (nome) values ("FANESE - Faculdade de Administração e Negócios de Sergipe");
INSERT INTO instituicao (nome) values ("FAMA - Faculdade Amadeus");
INSERT INTO instituicao (nome) values ("FSLF - Faculdade São Luis de França");
INSERT INTO instituicao (nome) values ("UNOPAR - Universidade Norte do Paraná");
INSERT INTO instituicao (nome) values ("FASER - Faculdade Sergipana");
INSERT INTO instituicao (nome) values ("FACAR - Faculdade de Aracaju");
INSERT INTO instituicao (nome) values ("UNIRB - Faculdade Serigy");
INSERT INTO instituicao (nome) values ("FAJAR - Faculdade Jardins");
INSERT INTO instituicao (nome) values ("FA - Faculdade Atlântico");
INSERT INTO instituicao (nome) values ("UniCOC - Sistema COC de Educação");
INSERT INTO instituicao (nome) values ("UNINASSAU - Faculdade Maurício de Nassau");
INSERT INTO instituicao (nome) values ("UnirG - Centro Universitário UnirG");
INSERT INTO instituicao (nome) values ("UNITINS - Fundação Universidade do Tocantins");
INSERT INTO instituicao (nome) values ("IFTO - Instituto Federal do Tocantins");
INSERT INTO instituicao (nome) values ("UFT - Universidade Federal do Tocantins");
INSERT INTO instituicao (nome) values ("CEULP/ULBRA - Centro Universitário Luterano de Palmas");
INSERT INTO instituicao (nome) values ("FACTO - Faculdade Católica do Tocantins");
INSERT INTO instituicao (nome) values ("FACDO - Faculdade Católica Dom Orione");
INSERT INTO instituicao (nome) values ("FACIT - Faculdade de Ciências do Tocantins");
INSERT INTO instituicao (nome) values ("FECIPAR - Faculdade de Educação Ciências e Letras de Paraíso");
INSERT INTO instituicao (nome) values ("FAPAL - Faculdade de Palmas");
INSERT INTO instituicao (nome) values ("FAG - Faculdade Guaraí");
INSERT INTO instituicao (nome) values ("FIESC - Faculdade Integrada de Ensino Superior de Colinas");
INSERT INTO instituicao (nome) values ("FASEC - Faculdade Serra do Carmo");
INSERT INTO instituicao (nome) values ("IEPO - Instituto de Ensino e Pesquisa Objetivo");
INSERT INTO instituicao (nome) values ("ITPAC - Instituto Tocantinense Presidente Antônio Carlos");
INSERT INTO instituicao (nome) values ("ITPAC Porto - Instituto Tocantinense Presidente Antônio Carlos de Porto Nacional");
INSERT INTO instituicao (nome) values ("UNEST - União Educacional de Ensino Superior do Médio Tocantins");
INSERT INTO instituicao (nome) values ("ETEP Faculdades - Escola Técnica Everardo Passos");
INSERT INTO instituicao (nome) values ("ETEC - Centro Paula Souza");
INSERT INTO instituicao (nome) values ("Faculdade de Tecnologia IBTA");
INSERT INTO instituicao (nome) values ("Faculdade Olavo Bilac");
INSERT INTO instituicao (nome) values ("Univap");
